---
title: Money Manager Dialog
---
flowchart TD
   START ==>|"command guarded"| STARTED
STARTED --o diamond1{STARTED branching}
   diamond1 ==>|"trigger guarded"| GROUP_JOIN_CONFIRM
   diamond1 ==>|"trigger guarded"| MENU
GROUP_JOIN_CONFIRM --o diamond2{GROUP_JOIN_CONFIRM branching}
   diamond2 ==>|"button CONFIRM_JOIN"| MENU
   diamond2 ==>|"button CANCEL"| MENU
MENU --o diamond3{MENU branching}
   diamond3 ==>|"button SHARED_ACCOUNTING"| GROUP_MANAGEMENT
   diamond3 ==>|"button CATEGORIES"| CATEGORY_MANAGEMENT
   diamond3 ==>|"text  guarded"| MENU
   diamond3 ==>|"voice"| MENU
   diamond3 ==>|"trigger guarded"| NLP_CONFIRM_CREATE_GROUP
   diamond3 ==>|"trigger guarded"| NLP_RESPONSE
   diamond3 ==>|"button NOTIFICATIONS"| NOTIFICATION_LIST
GROUP_MANAGEMENT --o diamond4{GROUP_MANAGEMENT branching}
   diamond4 ==>|"button CREATE_GROUP"| GROUP_CREATE_ENTER_NAME
   diamond4 ==>|"button INVITE_TO_GROUP"| GROUP_INVITE_SELECT
   diamond4 ==>|"button MY_GROUPS"| GROUP_LIST
   diamond4 ==>|"button GROUP_MEMBERS"| GROUP_MEMBERS
   diamond4 ==>|"button BACK_TO_MENU"| MENU
GROUP_CREATE_ENTER_NAME --o diamond5{GROUP_CREATE_ENTER_NAME branching}
   diamond5 ==>|"button CANCEL"| GROUP_MANAGEMENT
   diamond5 ==>|"button QUICK_GROUP_FAMILY"| GROUP_INVITE_SHOW
   diamond5 ==>|"button QUICK_GROUP_WITH_FRIEND"| GROUP_INVITE_SHOW
   diamond5 ==>|"button QUICK_GROUP_WORK"| GROUP_INVITE_SHOW
   diamond5 ==>|"button QUICK_GROUP_TRIP"| GROUP_INVITE_SHOW
   diamond5 ==>|"text "| GROUP_INVITE_SHOW
   GROUP_INVITE_SHOW ==>|"button BACK_TO_MENU"| GROUP_MANAGEMENT
GROUP_INVITE_SELECT --o diamond6{GROUP_INVITE_SELECT branching}
   diamond6 ==>|"button INVITE_TO_GROUP"| GROUP_INVITE_SHOW
   diamond6 ==>|"button CANCEL"| GROUP_MANAGEMENT
GROUP_LIST --o diamond7{GROUP_LIST branching}
   diamond7 ==>|"button SWITCH_GROUP"| GROUP_LIST
   diamond7 ==>|"button EDIT_GROUP"| GROUP_EDIT_SELECT
   diamond7 ==>|"button DELETE_GROUP"| GROUP_DELETE_SELECT
   diamond7 ==>|"button BACK_TO_MENU"| GROUP_MANAGEMENT
GROUP_EDIT_SELECT --o diamond8{GROUP_EDIT_SELECT branching}
   diamond8 ==>|"button EDIT_GROUP"| GROUP_EDIT_ENTER_NAME
   diamond8 ==>|"button CANCEL"| GROUP_LIST
GROUP_EDIT_ENTER_NAME --o diamond9{GROUP_EDIT_ENTER_NAME branching}
   diamond9 ==>|"text "| GROUP_LIST
   diamond9 ==>|"button CANCEL"| GROUP_EDIT_SELECT
GROUP_DELETE_SELECT --o diamond10{GROUP_DELETE_SELECT branching}
   diamond10 ==>|"button DELETE_GROUP"| GROUP_DELETE_CONFIRM
   diamond10 ==>|"button CANCEL"| GROUP_LIST
GROUP_DELETE_CONFIRM --o diamond11{GROUP_DELETE_CONFIRM branching}
   diamond11 ==>|"button CONFIRM_DELETE"| GROUP_LIST
   diamond11 ==>|"button CANCEL"| GROUP_DELETE_SELECT
   GROUP_MEMBERS ==>|"button BACK_TO_MENU"| GROUP_MANAGEMENT
CATEGORY_MANAGEMENT --o diamond12{CATEGORY_MANAGEMENT branching}
   diamond12 ==>|"button CREATE_CATEGORY guarded"| CATEGORY_CREATE_SELECT_TYPE
   diamond12 ==>|"button CREATE_CATEGORY guarded"| CATEGORY_NO_GROUP_WARNING
   diamond12 ==>|"button MY_CATEGORIES"| CATEGORY_LIST
   diamond12 ==>|"button DELETE_ALL_CATEGORIES"| CATEGORY_DELETE_ALL_CONFIRM
   diamond12 ==>|"button BACK_TO_MENU"| MENU
CATEGORY_CREATE_SELECT_TYPE --o diamond13{CATEGORY_CREATE_SELECT_TYPE branching}
   diamond13 ==>|"button CATEGORY_TYPE_EXPENSE"| CATEGORY_CREATE_ENTER_NAME
   diamond13 ==>|"button CATEGORY_TYPE_INCOME"| CATEGORY_CREATE_ENTER_NAME
   diamond13 ==>|"button CANCEL"| CATEGORY_MANAGEMENT
CATEGORY_CREATE_ENTER_NAME --o diamond14{CATEGORY_CREATE_ENTER_NAME branching}
   diamond14 ==>|"button CANCEL"| CATEGORY_CREATE_SELECT_TYPE
   diamond14 ==>|"text "| CATEGORY_MANAGEMENT
CATEGORY_NO_GROUP_WARNING --o diamond15{CATEGORY_NO_GROUP_WARNING branching}
   diamond15 ==>|"button CREATE_GROUP"| GROUP_MANAGEMENT
   diamond15 ==>|"button BACK_TO_MENU"| CATEGORY_MANAGEMENT
CATEGORY_LIST --o diamond16{CATEGORY_LIST branching}
   diamond16 ==>|"button CATEGORY_ITEM"| CATEGORY_ACTIONS
   diamond16 ==>|"button BACK_TO_MENU"| CATEGORY_MANAGEMENT
CATEGORY_ACTIONS --o diamond17{CATEGORY_ACTIONS branching}
   diamond17 ==>|"button EDIT_CATEGORY"| CATEGORY_EDIT_NAME
   diamond17 ==>|"button DELETE_CATEGORY_BUTTON"| CATEGORY_DELETE_CONFIRM
   diamond17 ==>|"button BACK_TO_MENU"| CATEGORY_LIST
CATEGORY_EDIT_NAME --o diamond18{CATEGORY_EDIT_NAME branching}
   diamond18 ==>|"button CANCEL"| CATEGORY_ACTIONS
   diamond18 ==>|"text "| CATEGORY_ACTIONS
CATEGORY_DELETE_CONFIRM --o diamond19{CATEGORY_DELETE_CONFIRM branching}
   diamond19 ==>|"button CONFIRM_DELETE"| CATEGORY_LIST
   diamond19 ==>|"button CANCEL"| CATEGORY_ACTIONS
CATEGORY_DELETE_ALL_CONFIRM --o diamond20{CATEGORY_DELETE_ALL_CONFIRM branching}
   diamond20 ==>|"button CONFIRM_DELETE"| CATEGORY_MANAGEMENT
   diamond20 ==>|"button CANCEL"| CATEGORY_MANAGEMENT
NLP_CONFIRM_CREATE_GROUP --o diamond21{NLP_CONFIRM_CREATE_GROUP branching}
   diamond21 ==>|"button CONFIRM_NLP_ACTION"| GROUP_INVITE_SHOW
   diamond21 ==>|"button CANCEL"| MENU
NLP_RESPONSE --o diamond22{NLP_RESPONSE branching}
   diamond22 ==>|"text  guarded"| MENU
   diamond22 ==>|"voice"| MENU
   diamond22 ==>|"trigger guarded"| NLP_CONFIRM_CREATE_GROUP
   diamond22 ==>|"trigger guarded"| NLP_RESPONSE
   diamond22 ==>|"button BACK_TO_MENU"| MENU
NOTIFICATION_LIST --o diamond23{NOTIFICATION_LIST branching}
   diamond23 ==>|"button CREATE_NOTIFICATION"| NOTIFICATION_CREATE_ENTER_NAME
   diamond23 ==>|"button EDIT_NOTIFICATION"| NOTIFICATION_EDIT_SELECT
   diamond23 ==>|"button DELETE_NOTIFICATION"| NOTIFICATION_DELETE_SELECT
   diamond23 ==>|"button DELETE_ALL_NOTIFICATIONS"| NOTIFICATION_DELETE_ALL_CONFIRM
   diamond23 ==>|"button BACK_TO_MENU"| MENU
NOTIFICATION_CREATE_ENTER_NAME --o diamond24{NOTIFICATION_CREATE_ENTER_NAME branching}
   diamond24 ==>|"text "| NOTIFICATION_CREATE_SELECT_PERIOD
   diamond24 ==>|"button CANCEL"| NOTIFICATION_LIST
NOTIFICATION_CREATE_SELECT_PERIOD --o diamond25{NOTIFICATION_CREATE_SELECT_PERIOD branching}
   diamond25 ==>|"button PERIOD_DAILY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond25 ==>|"button PERIOD_WEEKLY"| NOTIFICATION_CREATE_SELECT_DAY_OF_WEEK
   diamond25 ==>|"button PERIOD_BIWEEKLY"| NOTIFICATION_CREATE_SELECT_DAY_OF_WEEK
   diamond25 ==>|"button PERIOD_MONTHLY"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond25 ==>|"button PERIOD_BIMONTHLY"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond25 ==>|"button PERIOD_YEARLY"| NOTIFICATION_CREATE_SELECT_MONTH
   diamond25 ==>|"button PERIOD_CUSTOM"| NOTIFICATION_CREATE_CUSTOM_ENTER_N
   diamond25 ==>|"button CANCEL"| NOTIFICATION_CREATE_ENTER_NAME
NOTIFICATION_CREATE_ENTER_TIME --o diamond26{NOTIFICATION_CREATE_ENTER_TIME branching}
   diamond26 ==>|"text "| NOTIFICATION_CREATE_CONFIRM
   diamond26 ==>|"button CANCEL"| NOTIFICATION_CREATE_SELECT_PERIOD
NOTIFICATION_CREATE_CONFIRM --o diamond27{NOTIFICATION_CREATE_CONFIRM branching}
   diamond27 ==>|"button CONFIRM_CREATE_NOTIFICATION"| NOTIFICATION_LIST
   diamond27 ==>|"button CANCEL"| NOTIFICATION_LIST
NOTIFICATION_CREATE_SELECT_DAY_OF_WEEK --o diamond28{NOTIFICATION_CREATE_SELECT_DAY_OF_WEEK branching}
   diamond28 ==>|"button DAY_MONDAY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond28 ==>|"button DAY_TUESDAY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond28 ==>|"button DAY_WEDNESDAY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond28 ==>|"button DAY_THURSDAY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond28 ==>|"button DAY_FRIDAY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond28 ==>|"button DAY_SATURDAY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond28 ==>|"button DAY_SUNDAY"| NOTIFICATION_CREATE_ENTER_TIME
   diamond28 ==>|"button CANCEL"| NOTIFICATION_CREATE_SELECT_PERIOD
NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH --o diamond29{NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH branching}
   diamond29 ==>|"text "| NOTIFICATION_CREATE_ENTER_TIME
   diamond29 ==>|"button CANCEL"| NOTIFICATION_CREATE_SELECT_PERIOD
NOTIFICATION_CREATE_SELECT_MONTH --o diamond30{NOTIFICATION_CREATE_SELECT_MONTH branching}
   diamond30 ==>|"button MONTH_JANUARY"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_FEBRUARY"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_MARCH"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_APRIL"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_MAY"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_JUNE"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_JULY"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_AUGUST"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_SEPTEMBER"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_OCTOBER"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_NOVEMBER"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button MONTH_DECEMBER"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond30 ==>|"button CANCEL"| NOTIFICATION_CREATE_SELECT_PERIOD
NOTIFICATION_CREATE_CUSTOM_ENTER_N --o diamond31{NOTIFICATION_CREATE_CUSTOM_ENTER_N branching}
   diamond31 ==>|"text "| NOTIFICATION_CREATE_CUSTOM_SELECT_UNIT
   diamond31 ==>|"button CANCEL"| NOTIFICATION_CREATE_SELECT_PERIOD
NOTIFICATION_CREATE_CUSTOM_SELECT_UNIT --o diamond32{NOTIFICATION_CREATE_CUSTOM_SELECT_UNIT branching}
   diamond32 ==>|"button CUSTOM_UNIT_DAYS"| NOTIFICATION_CREATE_ENTER_TIME
   diamond32 ==>|"button CUSTOM_UNIT_WEEKS"| NOTIFICATION_CREATE_SELECT_DAY_OF_WEEK
   diamond32 ==>|"button CUSTOM_UNIT_MONTHS"| NOTIFICATION_CREATE_ENTER_DAY_OF_MONTH
   diamond32 ==>|"button CUSTOM_UNIT_YEARS"| NOTIFICATION_CREATE_SELECT_MONTH
   diamond32 ==>|"button CANCEL"| NOTIFICATION_CREATE_CUSTOM_ENTER_N
NOTIFICATION_EDIT_SELECT --o diamond33{NOTIFICATION_EDIT_SELECT branching}
   diamond33 ==>|"button NOTIFICATION_ITEM"| NOTIFICATION_EDIT_MENU
   diamond33 ==>|"button CANCEL"| NOTIFICATION_LIST
NOTIFICATION_EDIT_MENU --o diamond34{NOTIFICATION_EDIT_MENU branching}
   diamond34 ==>|"button EDIT_NOTIFICATION_NAME"| NOTIFICATION_EDIT_ENTER_NAME
   diamond34 ==>|"button EDIT_NOTIFICATION_PERIOD"| NOTIFICATION_EDIT_SELECT_PERIOD
   diamond34 ==>|"button BACK_TO_MENU"| NOTIFICATION_LIST
NOTIFICATION_EDIT_ENTER_NAME --o diamond35{NOTIFICATION_EDIT_ENTER_NAME branching}
   diamond35 ==>|"text "| NOTIFICATION_EDIT_MENU
   diamond35 ==>|"button CANCEL"| NOTIFICATION_EDIT_MENU
NOTIFICATION_EDIT_SELECT_PERIOD --o diamond36{NOTIFICATION_EDIT_SELECT_PERIOD branching}
   diamond36 ==>|"button PERIOD_DAILY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond36 ==>|"button PERIOD_WEEKLY"| NOTIFICATION_EDIT_SELECT_DAY_OF_WEEK
   diamond36 ==>|"button PERIOD_BIWEEKLY"| NOTIFICATION_EDIT_SELECT_DAY_OF_WEEK
   diamond36 ==>|"button PERIOD_MONTHLY"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond36 ==>|"button PERIOD_BIMONTHLY"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond36 ==>|"button PERIOD_YEARLY"| NOTIFICATION_EDIT_SELECT_MONTH
   diamond36 ==>|"button PERIOD_CUSTOM"| NOTIFICATION_EDIT_CUSTOM_ENTER_N
   diamond36 ==>|"button CANCEL"| NOTIFICATION_EDIT_MENU
NOTIFICATION_EDIT_ENTER_TIME --o diamond37{NOTIFICATION_EDIT_ENTER_TIME branching}
   diamond37 ==>|"text "| NOTIFICATION_EDIT_CONFIRM
   diamond37 ==>|"button CANCEL"| NOTIFICATION_EDIT_SELECT_PERIOD
NOTIFICATION_EDIT_CONFIRM --o diamond38{NOTIFICATION_EDIT_CONFIRM branching}
   diamond38 ==>|"button CONFIRM_EDIT_NOTIFICATION"| NOTIFICATION_EDIT_MENU
   diamond38 ==>|"button CANCEL"| NOTIFICATION_EDIT_MENU
NOTIFICATION_EDIT_SELECT_DAY_OF_WEEK --o diamond39{NOTIFICATION_EDIT_SELECT_DAY_OF_WEEK branching}
   diamond39 ==>|"button DAY_MONDAY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond39 ==>|"button DAY_TUESDAY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond39 ==>|"button DAY_WEDNESDAY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond39 ==>|"button DAY_THURSDAY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond39 ==>|"button DAY_FRIDAY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond39 ==>|"button DAY_SATURDAY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond39 ==>|"button DAY_SUNDAY"| NOTIFICATION_EDIT_ENTER_TIME
   diamond39 ==>|"button CANCEL"| NOTIFICATION_EDIT_SELECT_PERIOD
NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH --o diamond40{NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH branching}
   diamond40 ==>|"text "| NOTIFICATION_EDIT_ENTER_TIME
   diamond40 ==>|"button CANCEL"| NOTIFICATION_EDIT_SELECT_PERIOD
NOTIFICATION_EDIT_SELECT_MONTH --o diamond41{NOTIFICATION_EDIT_SELECT_MONTH branching}
   diamond41 ==>|"button MONTH_JANUARY"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_FEBRUARY"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_MARCH"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_APRIL"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_MAY"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_JUNE"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_JULY"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_AUGUST"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_SEPTEMBER"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_OCTOBER"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_NOVEMBER"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button MONTH_DECEMBER"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond41 ==>|"button CANCEL"| NOTIFICATION_EDIT_SELECT_PERIOD
NOTIFICATION_EDIT_CUSTOM_ENTER_N --o diamond42{NOTIFICATION_EDIT_CUSTOM_ENTER_N branching}
   diamond42 ==>|"text "| NOTIFICATION_EDIT_CUSTOM_SELECT_UNIT
   diamond42 ==>|"button CANCEL"| NOTIFICATION_EDIT_SELECT_PERIOD
NOTIFICATION_EDIT_CUSTOM_SELECT_UNIT --o diamond43{NOTIFICATION_EDIT_CUSTOM_SELECT_UNIT branching}
   diamond43 ==>|"button CUSTOM_UNIT_DAYS"| NOTIFICATION_EDIT_ENTER_TIME
   diamond43 ==>|"button CUSTOM_UNIT_WEEKS"| NOTIFICATION_EDIT_SELECT_DAY_OF_WEEK
   diamond43 ==>|"button CUSTOM_UNIT_MONTHS"| NOTIFICATION_EDIT_ENTER_DAY_OF_MONTH
   diamond43 ==>|"button CUSTOM_UNIT_YEARS"| NOTIFICATION_EDIT_SELECT_MONTH
   diamond43 ==>|"button CANCEL"| NOTIFICATION_EDIT_CUSTOM_ENTER_N
NOTIFICATION_DELETE_SELECT --o diamond44{NOTIFICATION_DELETE_SELECT branching}
   diamond44 ==>|"button NOTIFICATION_ITEM"| NOTIFICATION_DELETE_CONFIRM
   diamond44 ==>|"button CANCEL"| NOTIFICATION_LIST
NOTIFICATION_DELETE_CONFIRM --o diamond45{NOTIFICATION_DELETE_CONFIRM branching}
   diamond45 ==>|"button CONFIRM_DELETE"| NOTIFICATION_LIST
   diamond45 ==>|"button CANCEL"| NOTIFICATION_LIST
NOTIFICATION_DELETE_ALL_CONFIRM --o diamond46{NOTIFICATION_DELETE_ALL_CONFIRM branching}
   diamond46 ==>|"button CONFIRM_DELETE"| NOTIFICATION_LIST
   diamond46 ==>|"button CANCEL"| NOTIFICATION_LIST
