---
title: Money Manager Dialog
---
flowchart TD
   START ==>|"command guarded"| STARTED
STARTED --o diamond1{STARTED branching}
   diamond1 ==>|"trigger guarded"| GROUP_JOIN_CONFIRM
   diamond1 ==>|"trigger guarded"| MENU
GROUP_JOIN_CONFIRM --o diamond2{GROUP_JOIN_CONFIRM branching}
   diamond2 ==>|"button CONFIRM_JOIN"| MENU
   diamond2 ==>|"button CANCEL"| MENU
   MENU ==>|"button SHARED_ACCOUNTING"| GROUP_MANAGEMENT
GROUP_MANAGEMENT --o diamond3{GROUP_MANAGEMENT branching}
   diamond3 ==>|"button CREATE_GROUP"| GROUP_CREATE_ENTER_NAME
   diamond3 ==>|"button MY_GROUPS"| GROUP_LIST
   diamond3 ==>|"button GROUP_MEMBERS"| GROUP_MEMBERS
   diamond3 ==>|"button BACK_TO_MENU"| MENU
GROUP_CREATE_ENTER_NAME --o diamond4{GROUP_CREATE_ENTER_NAME branching}
   diamond4 ==>|"button CANCEL"| GROUP_MANAGEMENT
   diamond4 ==>|"button QUICK_GROUP_FAMILY"| GROUP_INVITE_SHOW
   diamond4 ==>|"button QUICK_GROUP_WITH_FRIEND"| GROUP_INVITE_SHOW
   diamond4 ==>|"button QUICK_GROUP_WORK"| GROUP_INVITE_SHOW
   diamond4 ==>|"button QUICK_GROUP_TRIP"| GROUP_INVITE_SHOW
   diamond4 ==>|"text "| GROUP_INVITE_SHOW
   GROUP_INVITE_SHOW ==>|"button BACK_TO_MENU"| GROUP_MANAGEMENT
GROUP_LIST --o diamond5{GROUP_LIST branching}
   diamond5 ==>|"button SWITCH_GROUP"| GROUP_LIST
   diamond5 ==>|"button EDIT_GROUP"| GROUP_EDIT_SELECT
   diamond5 ==>|"button DELETE_GROUP"| GROUP_DELETE_SELECT
   diamond5 ==>|"button BACK_TO_MENU"| GROUP_MANAGEMENT
GROUP_EDIT_SELECT --o diamond6{GROUP_EDIT_SELECT branching}
   diamond6 ==>|"button EDIT_GROUP"| GROUP_EDIT_ENTER_NAME
   diamond6 ==>|"button CANCEL"| GROUP_LIST
GROUP_EDIT_ENTER_NAME --o diamond7{GROUP_EDIT_ENTER_NAME branching}
   diamond7 ==>|"text "| GROUP_LIST
   diamond7 ==>|"button CANCEL"| GROUP_EDIT_SELECT
GROUP_DELETE_SELECT --o diamond8{GROUP_DELETE_SELECT branching}
   diamond8 ==>|"button DELETE_GROUP"| GROUP_DELETE_CONFIRM
   diamond8 ==>|"button CANCEL"| GROUP_LIST
GROUP_DELETE_CONFIRM --o diamond9{GROUP_DELETE_CONFIRM branching}
   diamond9 ==>|"button CONFIRM_DELETE"| GROUP_LIST
   diamond9 ==>|"button CANCEL"| GROUP_DELETE_SELECT
   GROUP_MEMBERS ==>|"button BACK_TO_MENU"| GROUP_MANAGEMENT
