chat-machinist:
  visualize: true
  applicationName: "Money Manager AI"
  persistence:
    type: mongodb
  bot:
    name: ${BOT_NAME}
    token: ${BOT_TOKEN}
  alert:
    telegramChatId: ${ALERT_CHAT_ID:#{null}}

gemini:
  api-key: ${GEMINI_API_KEY}
  model: gemini-2.5-flash-lite

telegram:
  file:
    max-voice-duration-seconds: 180 # 3 минуты
    max-file-size-bytes: 2097152 # 2 MB (2 * 1024 * 1024)
    api-url: "https://api.telegram.org/file/bot"

debug: false
spring:
  mongodb:
    database: moneyManagerBot
    host: ${MONGO_HOST:localhost}
    username: ${MONGO_USERNAME}
    password: ${MONGO_PASSWORD}
    port: 27019
  data:
    mongodb:
      auto-index-creation: true
  main:
    banner-mode: off